### ISSUE TITLE
regression? 4.9, 4.10rc1 crash on reboot

### ISSUE THREAD

**Issue by az143** [troglobit/finit#429]
situation: we have a fairly straightforward finit configuration set which runs up a few services, 
sequenced using a few custom conditions, and one sys/pwr/fail task that calls `initctl poweroff`. 
with 4.8, both power-fail-triggered and explicitly triggered reboots and shutdowns work fine and reliably. 
with 4.9 and the same configuration rebooting doesn't work.

using 4.9, `initctl debug` followed by `initctl reboot`:
the last lines displayed are 

```
finit[1]: sm_step():state: runlevel/wait, runlevel: 6, newlevel: -1, teardown: 1, reload: 0
finit[1]: sm_step():All services have been stopped, calling runlevel change hooks ...
...a list of many things stopped or halted...
finit[1]: plugin_unregister():bootmisc exiting ...
```
immediately followed by a panic: 'finit[1]:[  177.502157] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b'

using 4.9, `initctl debug`, then triggering the sys/pwr/fail  with SIGPWR: and the unit shuts down successfully;
the log output is very similar but following the bootmisc exiting, we get alsa-utils, tty, procps ... exiting lines and the shutdown progresses as expected.

active plugins: alsa-utils.so  netlink.so  sys.so bootmisc.so  pidfile.so  tty.so procps.so
urandom.so hook-scripts.so   rtc.so      usr.so
hook scripts: one in sys/down (but things don't progress that far in the failure scenario)
no post: scripts whatsoever.

i've tried to diff the debug output of a succeeding vs. failing shutdown run, and apart from the 
expected numeric pid and arg 0xwhatever differences, there doesn't seem to be anything majorly different.  after finit logs 'All services have been stopped', the listing of service states looks pretty much the same (except for the powerfail condition being on vs. off). i'm attaching both those logs.

joachim, any ideas as to what the problem might be? any suggestions for debugging this further would be highly appreciated.

[shutdown_fails.txt](https://github.com/user-attachments/files/18936038/shutdown_fails.txt)
[shutdown_succeeds.txt](https://github.com/user-attachments/files/18936039/shutdown_succeeds.txt)

**Comment by troglobit** [comment]
Ouch, not good, I'll have a look at it! 😟 

I'm in the late stages of the next release already, so this was really good timing.

**Comment by troglobit** [comment]
Hmm, unable to reproduce so far, but `exitcode=0x0000000b` seems to indicate Finit was killed by SIGSEGV.  

One of the major changes in the upcoming Finit v4.10 is a few more states for both the service state machine and the main Finit state machine, this to more safely handle lingering services and properly wait for any cleanup jobs to return before freeing internal resources.

I've already made a [4.10-rc1 release](https://github.com/troglobit/finit/releases/tag/4.10-rc1) with these fixes.  

Maybe you can give it a quick spin to see if it fixes the issues you see?

**Comment by az143** [comment]
On Sun, 23 Feb 2025 21:44:50 -0800, Joachim Wiberg writes:
>Hmm, unable to reproduce so far, but `exitcode=0x0000000b` seems to
>indicate Finit was killed by SIGSEGV.

possibly relevant in that context: both 4.8 and 4.9 were built locally,
and both against the same combo of libite5 2.2.0, libuev2 2.3.1 and libc6 2.31
(ie. debian bullseye, not bookworm).

>Maybe you can give it a quick spin to see if it fixes the issues you see?

thanks, i'll try that tomorrow and will report back soonest.


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + https://snafu.priv.at/
All that blue light from Orthanc at night? That was
Saruman, trying to moderate
 -- news.admin.palantir-abuse.sightings.

**Comment by az143** [comment]
i have a tiny bit more info, maybe relevant? 

my build of 4.9 that fails one one machine works on an identical separate machine (same arm board, same debian release, same libraries, same configs etc). 

the debug logs look super-similar, but after the `All services have been stopped` the plugins record their exiting in a different order, and they all do exit successfully.

i  looked at that sequence, and the raw unsorted list of plugins in /lib/finit/plugins (if looked at with `ls --sort-n`) seems to correspond to the plugin exit message sequence.

on the failing box the order has bootmisc near the top:

```ls -1 --sort=n /lib/finit/plugins/ 
urandom.so
netlink.so
bootmisc.so
alsa-utils.so
tty.so
procps.so
usr.so
pidfile.so
x11-common.so.disabled
dbus.so.disabled
hook-scripts.so
rtc.so
sys.so
```
and the crash happens after the bootmisc.so exit message.

on the working machine the sequence is 
```
ls -1 --sort=n /lib/finit/plugins/
hook-scripts.so
sys.so
netlink.so
alsa-utils.so
urandom.so
dbus.so.disabled
rtc.so
x11-common.so.disabled
procps.so
tty.so
bootmisc.so
usr.so
pidfile.so
```
and the plugin unregister messages line up with that.

**Comment by troglobit** [comment]
I don't think we can draw any conclusions from that. If this is what it seems to be, memory corruption, then all bets are off anyway.

**Comment by az143** [comment]
yes, the plugin sequence seems to have been a red herring. 

i've now compiled and run 4.10-rc1, and the behaviour is exactly the same: if i send a SIGPWR to finit it shuts down fine. if i run `initctl poweroff` it crashes. this happens every time.
i'm attaching the two new logs, created back to back just a few minutes ago.

any suggestions what i might try to get finit to tell me more about what it is trying to do and where it goes south?

[4.10rc1-poweroff-fails.txt](https://github.com/user-attachments/files/18950752/4.10rc1-poweroff-fails.txt)
[4.10rc1-sigpwr-works.txt](https://github.com/user-attachments/files/18950753/4.10rc1-sigpwr-works.txt)

**Comment by az143** [comment]
another bit of info: with 4.10rc1 and a freshly booted machine: 
if i `kill -INT 1` followed by `kill -TERM 1`  roughly 15 seconds later, then finit succeeds in rebooting.
if i just `kill -TERM 1`, then finit crashes.

[INT-then-TERM-works.txt](https://github.com/user-attachments/files/18951997/INT-then-TERM-works.txt)
[just-TERM-fails.txt](https://github.com/user-attachments/files/18951998/just-TERM-fails.txt)

**Comment by troglobit** [comment]
Hmm, interesting, but shouldn't really affect things since you've not mapped anything to that condition.

I'm really at a loss here, and I've gone through the diff between 4.8 and 4.9.  So my guess is this bug, whatever it is, has been dormant for a while and triggered by the changes in 4.9.  Unless there's something in your environment that's changed?  E.g., have you tried rebuilding 4.8 and still don't get the problem?

It's frustrating I cannot replicate the issue myself.  I have newer versions of libuev et al, which could affect things ... could you perhaps include more information about how Finit is built, e.g., `config.log`?  Would be great if we could nail this one down.

I've tried running GDB against Finit a few times.  In this case we have everything working up until completion of shutdown, so it should be easier.  Usually I use `gdbserver --attach IP:3333 1 &` on the system with Finit, and then `gdb-multiarch` on a connected system, calling `target remote IP:3333` followed by `cont`.  Then you can run `initctl poweroff` to trigger the bug, and `bt full` in gdb.  (Of course, for this to work, you need to build Finit with symbols.)

**Comment by az143** [comment]
indeed, puzzling why that raise of the condition makes any difference at all. (i ran the TERM vs. INT-then-TERM experiment a good 10 times, just to be sure that it's not a one-off fluke....)

my 4.8 and the 4.9 and 4.10 test builds are all against the same baseline chroot, with the usual debianish reproducible build settings so i don't think a rebuild of 4.8 will make it fail - but i'll try that tomorrow.

newer libs: i've had zero success building against debian's libuev3 (=2.4.0), which is why my baseline chroot is  still using bullseye. any finit that i've build against that so far fails to progress beyond starting of an mdev. i may retry with local builds of the newest libuev and libite, but that'll have to wait a few days.

i'll certainly check with gdb, but again this will take a few days.

let's leave the bug open for now, but given the odd nature of it and the fact  that 4.8 works fine i don't think it's high priority.

**Comment by troglobit** [comment]
OK, we leave it open, and not-a-blocker for the v4.10 release.

One thing to look out for is that libuEv v2.4.x move to a 64-bit `time_t`, so you need to ensure Finit (and all other related applications) are rebuilt with `CPPFLAGS += -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64`

Good luck with the debugging, and please let me know if you need someone to bounce ideas off!

**Comment by aanderse** [comment]
i thought i had done something wrong with my machine configuration.... but i ran into a hard crash on poweroff recently too

![Image](https://github.com/user-attachments/assets/bf119c2a-175d-4d92-8f30-aea8badbc8d7)

i will try to find some time tonight to report exact versions and roll back to older commits

**Comment by troglobit** [comment]
Sorry for the late reply, I'm down with the flu for the moment, but this looks *really* interesting!  Here we can clearly see the segfault is in libuEv, and ...

 - In libuEv v2.4.0 we stepped the ABI version to 3.0.0
 - In libuEv v2.4.1 the ABI version was unfortunately not stepped, but a [critical bug](troglobit/libuev/issues/27) was fixed!

In retrospect, it is very likely this bug is the root cause of both your problems.
So it would be great if you could verify this theory @aanderse

**Comment by az143** [comment]
i've got a bit more info again: i've now locally recompiled all of libite 2.5.1 and libuev 2.4.0 and finit 4.10rc1 with the 64bit defines forced in. this now starts and works, except my original shutdown issue remains unchanged.

gdb'ing things wasn't successful, as the crash happens after the network is gone and after all the other processes 
have been killed.
so i've resorted to printf-debugging, and i think i'm getting closer.

as far as i can tell right now, the problem is somewhere in `plugin_exit()`, in the iterator magic.
i've got two relevant printfs, on in sig.c in `do_shutdown` just before `plugin_exit` is called and one in the iterator in plugin_exit (just printing p->name and p->handle).

scenario:
if i `kill -INT 1` and then `kill -TERM 1`, then things are fine, the iterator printf shows up and plugin_unregister messages show up  and shutdown or reboot succeeds.
if i just run `kill -TERM 1`, then the printf before calling `plugin_exit()` is the last thing i see, followed by the kernel panic.

in my log output the printfs near the `dlclose()` and various plugin_unregister messages are interspersed, not surprising given the plugin_unregister stuff is used as destructor.

looking at plugin_unregister i see the 'not called' comment, and it seems to also massage the same queue that plugin_exit() traverses. could that be what causes the crash?

**Comment by az143** [comment]
looks like it's the dclose iterator blows up in TAILQ_NEXT.

the attached patch adds printfs, fflushes and 1s delays to `do_shutdown` and `plugin_exit` and `plugin_unregister`; the delays seemed necessary to get the printf output onto my serial console no matter what happens next.

with that, finit 4.10rc1 now crashes every single time about halfway through the `dlclose` iteration over the plugins - see the 'az: something' lines in the attached log outputs (without and with initctl debug). the free of plugin name succeeds, the dlclose succeeds but the following `TAILQ_NEXT` blows up.

(note: i've removed some of the non-relevant lines from the two logs.)

my question: is it actually useful/necessary/desirable to dlclose the plugins on shutdown? does the plugin queue have to be cleaned up at that time?

[debug-patch.txt](https://github.com/user-attachments/files/18999917/debug-patch.txt)
[slow-fail.txt](https://github.com/user-attachments/files/18999918/slow-fail.txt)
[slow-fail-verbose.txt](https://github.com/user-attachments/files/18999916/slow-fail-verbose.txt)

**Comment by aanderse** [comment]
@troglobit - please ignore this thread until you're feeling better 😄

couple notes

- i get the same results with both versions `2.4.0` and `2.4.1` of `libuev`
- my `finit` is currently 617609cbc5d9e1974d9e02accfae23bb29a05c74
- running with `finit.debug=true` - the last thing i see before crash is `finit[1]: plugin_unregister():`... twice for a few plugins then nothing after that

i didn't have much time tonight so i couldn't start rolling back to older versions of `finit`... i hope to do that tomorrow night

@az143 - if there is any information i can provide to help you, or any patches you want me to try, feel free to mention

thanks all

**Comment by az143** [comment]
@aanderse: to sidestep this issue i've patched out the plugin_exit altogether, and that works fine for our use case (which is physical machines, not containers); see attached. 

[no-plugin-unload.txt](https://github.com/user-attachments/files/19000790/no-plugin-unload.txt)

once joachim is well again he may very well come up with a good reason why finit does need to run plugin_exit, in which case the plugin queue iteration needs to be looked at further.

**Comment by troglobit** [comment]
Still quite a bit under the weather, but during one of my lucid moments I had a look at the plugins once more.

One thing I didn't consider before is that in v4.9 we added a periodic timer to the RTC plugin, which is not stopped properly at plugin exit.  This could be it, but frustratingly enough I still cannot replicate any of your problems, so I hope one of you can test this theory by disabling the plugin.

**Comment by aanderse** [comment]
i can confirm: i disabled the `rtc` plugin and am able to reboot without issue 👍

> One thing to look out for is that libuEv v2.4.x move to a 64-bit time_t, so you need to ensure Finit (and all other related applications) are rebuilt with CPPFLAGS += -D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64

btw i am running this on a linux laptop running 64 bit linux so `time_t` is definitely a 64bit data type

**Comment by troglobit** [comment]
> i can confirm: i disabled the `rtc` plugin and am able to reboot without issue 👍

That's great news, thank you so much for taking the time to verify! 🙏 

> my question: is it actually useful/necessary/desirable to dlclose the plugins on shutdown? does the plugin queue have to be cleaned up at that time?

Good question!  Generally it's a good idea to clean up after yourself, but in this case we're shutting down, and the kernel can reclaim the memory when we check out.  We should probably drop the idea of ever being able to unload plugins.  However, the PLUGIN_EXIT() code of each plugin must run, that's part of the plugin contract.  There are users out there that maintain their own Finit plugins.

For now I'll keep the code as-is but add a new issue to plan for an overhaul of the plugins in 5.0, at least dropping the `dlclose()`.  There's also a few that have become foundational and are more core functionality in Finit today, so the term "plugin" for them is quite misleading.  There have been questions about this in the past.

**Comment by troglobit** [comment]
The fixes tag in the commit auto-closed this issue, but please let me know if a23e152 really solves the issue for you @az143 & @aanderse -- otherwise we'll reopen this immediately!

**Comment by az143** [comment]
On Fri, 28 Feb 2025 02:23:46 -0800, Joachim Wiberg writes:
>The fixes tag in the commit auto-closed this issue, but please let me know
>if a23e152 really solves the issue for you @az143 & @aanderse -- otherwise
>we'll reopen this immediately!

i'll check this first thing monday and report back.


-- 
Alexander Zangerl + GPG Key 2FCCF66BB963BD5F + https://snafu.priv.at/
To rephrase, spam is not the answer. Spam is the question.
Death is not the answer, but pretty close to it. -- Vadik

**Comment by aanderse** [comment]
@troglobit - all good here, no crash on reboot

as always thanks for your efforts 🙇‍♂

**Comment by az143** [comment]
i've run a few more checks and with https://github.com/troglobit/finit/commit/a23e152f6b2c883130bb0a4bfa55ef304294a369 shutdown works fine now. thank you!

**Comment by troglobit** [comment]
Wohoo, thank you so much both of you for hanging in there and helping out testing the fix! 🙏
